// source/browser-application/game-points/GamePointsAudio.vue
<script setup lang="ts">
import { storeToRefs } from "pinia";
import { onMounted } from "vue";
import { useOnline } from "@vueuse/core";
import { isUndefined } from "@sindresorhus/is";
import { useGameStore } from "../game-store/game-store.js";

const isOnline = useOnline();
const gameStore = useGameStore();
const { isAudioPlaying } = storeToRefs(gameStore);

function onAudioError(): void {
	isAudioPlaying.value = false;
}

function onAudioWaiting(): void {
	if (!isOnline.value) {
		isAudioPlaying.value = false;
	}
}

onMounted(async () => {
	const audioPlaylist = await gameStore.generateGamePointsAudioPlaylist();

	const audioObjects = audioPlaylist.match({
		Ok(playlistItemAPIPaths) {
			return playlistItemAPIPaths.map((playlistItemAPIPath) => {
				return new Audio(playlistItemAPIPath);
			});
		},
		Err() {
			return [];
		}
	});

	let currentAudioIndex = 0;

	function playNext(): void {
		if (currentAudioIndex < audioObjects.length) {
			const currentAudio = audioObjects[currentAudioIndex];

			if (!isUndefined(currentAudio)) {
				currentAudio.addEventListener("error", onAudioError);
				currentAudio.addEventListener("waiting", onAudioWaiting);
				currentAudio.addEventListener("ended", playNext);

				// eslint-disable-next-line promise/catch-or-return, promise/prefer-await-to-then, @typescript-eslint/no-floating-promises -- needs to be refactored
				currentAudio.play().then(() => {
					currentAudioIndex += 1;
				});
			}
		} else {
			isAudioPlaying.value = false;
		}
	}

	playNext();
});
</script>

<template>
	<audio />
</template>

// source/browser-application/game-points/GamePointsAudio.tsx
import { useEffect, type FunctionComponent } from "react";
import { useStore } from "zustand";
import { isUndefined } from "@sindresorhus/is";
import { useApplicationContext, type BrowserRuntime, type AudioElementFactory } from "../context/app-context.js";

function createAudioElements(
	playlistItemApiPaths: readonly string[],
	audioElementFactory: AudioElementFactory
): HTMLAudioElement[] {
	return playlistItemApiPaths.map((playlistItemApiPath) => {
		return audioElementFactory.createAudioElement(playlistItemApiPath);
	});
}

async function waitForAudioToEnd(audioElement: HTMLAudioElement, browserRuntime: BrowserRuntime): Promise<boolean> {
	return new Promise((resolve) => {
		audioElement.addEventListener(
			"error",
			() => {
				resolve(false);
			},
			{ once: true }
		);
		audioElement.addEventListener(
			"waiting",
			() => {
				if (!browserRuntime.isOnline()) {
					resolve(false);
				}
			},
			{ once: true }
		);
		audioElement.addEventListener(
			"ended",
			() => {
				resolve(true);
			},
			{ once: true }
		);
	});
}

async function playAudioElement(audioElement: HTMLAudioElement, browserRuntime: BrowserRuntime): Promise<boolean> {
	const audioEnded = waitForAudioToEnd(audioElement, browserRuntime);
	await audioElement.play();
	return audioEnded;
}

export const GamePointsAudio: FunctionComponent = () => {
	const applicationContext = useApplicationContext();
	const { browserRuntime, audioElementFactory, gameStore } = applicationContext;
	const isAudioPlaying = useStore(gameStore, (state) => {
		return state.isAudioPlaying;
	});

	useEffect(() => {
		let isCancelled = false;

		async function playAudio(): Promise<void> {
			const audioPlaylist = await gameStore.getState().generateGamePointsAudioPlaylist();
			const audioObjects = audioPlaylist.match({
				Ok(playlistItemApiPaths) {
					return createAudioElements(playlistItemApiPaths, audioElementFactory);
				},
				Err() {
					return [];
				}
			});

			let currentAudioIndex = 0;

			while (currentAudioIndex < audioObjects.length) {
				if (isCancelled) {
					return;
				}

				const currentAudio = audioObjects[currentAudioIndex];
				if (isUndefined(currentAudio)) {
					return;
				}

				const playedSuccessfully = await playAudioElement(currentAudio, browserRuntime);
				if (!playedSuccessfully) {
					gameStore.getState().setIsAudioPlaying(false);
					return;
				}

				currentAudioIndex += 1;
			}

			gameStore.getState().setIsAudioPlaying(false);
		}

		if (isAudioPlaying) {
			void playAudio();
		}

		return () => {
			isCancelled = true;
		};
	}, [audioElementFactory, browserRuntime, gameStore, isAudioPlaying]);

	return <audio />;
};
