// source/game-over/GameOver.vue
<script setup lang="ts">
import { computed } from "vue";
import { storeToRefs } from "pinia";
import { useGameStore } from "../game-store/game-store.js";
import { determineWinnerTeam } from "../team/teams.js";

const gameStore = useGameStore();
const { team1, team2, isAudioPlaying, shouldPlayAudio } = storeToRefs(gameStore);

const isReplayAudioButtonDisabled = computed(() => {
	return isAudioPlaying.value || !shouldPlayAudio.value;
});

const wonText = determineWinnerTeam(team1, team2).mapOr("Gewonnen hat: ???", (team) => {
	return `Gewonnen hat: Team "${team.value.teamName}"`;
});
</script>

<template>
	<section class="col-span-full my-8 grid grid-cols-subgrid grid-rows-3 gap-2 lg:col-start-2 lg:col-end-6">
		<h1 class="col-span-full place-self-center">{{ wonText }}</h1>

		<button
			type="button"
			class="btn col-span-full mx-10 md:col-start-2 md:col-end-4 md:mx-0"
			@click="gameStore.startNewGame"
		>
			Neues Spiel
		</button>
		<button
			:disabled="isReplayAudioButtonDisabled"
			type="button"
			class="btn col-span-full mx-10 md:col-start-2 md:col-end-4 md:mx-0"
			@click="isAudioPlaying = true"
		>
			Punktestand vorlesen
		</button>
	</section>
</template>

// source/lib/game-over/GameOver.svelte
<script lang="ts">
	import GameOverAudio from "../audio/GameOverAudio.svelte";
	import { settingsStore } from "../settings/settings-store.js";
	import { gameStore } from "../game-store/game-store.js";
	import { determineWinnerTeam } from "../team/teams.js";

	export let apiRouteBaseUrl: URL;

	let isAudioPlaying = true;

	const winnerTeam = determineWinnerTeam($gameStore.teams);
	const wonText = winnerTeam.mapOr("Gewonnen hat: ???", (team) => {
		return `Gewonnen hat: Team "${team.teamName}"`;
	});

	function onAudioEnded(): void {
		isAudioPlaying = false;
	}

	function replayAudio(): void {
		isAudioPlaying = true;
	}
</script>

<section
	class="flex flex-col gap-6 items-center p-8 m-10 mt-16 bg-opacity-90 rounded-lg shadow-md sm:mx-auto sm:max-w-lg bg-slate-800"
>
	<h1>{wonText}</h1>

	<button on:click={gameStore.startNewGame} type="button" class="btn">Neues Spiel</button>
	<button disabled={isAudioPlaying || !$settingsStore.audioEnabled} on:click={replayAudio} type="button" class="btn"
		>Punktestand vorlesen</button
	>

	{#if $settingsStore.audioEnabled && isAudioPlaying}
		<GameOverAudio {apiRouteBaseUrl} on:audioEnded={onAudioEnded} />
	{/if}
</section>
