// source/browser-application/game-over/GameOver.tsx
import { useEffect, useState, type FunctionComponent } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { useStore } from "zustand";
import { useNavigate } from "react-router-dom";
import { tryOrElse } from "true-myth/task";
import { useApplicationContext } from "../context/app-context.js";
import { Button } from "../ui/button.js";

export const GameOver: FunctionComponent = () => {
	const navigate = useNavigate();
	const applicationContext = useApplicationContext();
	const { gameStore, trpc } = applicationContext;
	const queryClient = useQueryClient();
	const team1 = useStore(gameStore, (state) => {
		return state.team1;
	});
	const team2 = useStore(gameStore, (state) => {
		return state.team2;
	});
	const isAudioPlaying = useStore(gameStore, (state) => {
		return state.isAudioPlaying;
	});
	const [wonText, setWonText] = useState("");

	useEffect(() => {
		const determineWinnerTeam = async (): Promise<void> => {
			const winnerTeamResult = await tryOrElse(
				(error: unknown) => {
					return new Error("Could not determine winner team", { cause: error });
				},
				async () => {
					return queryClient.query(trpc.game.determineWinnerTeam.queryOptions({ team1, team2 }));
				}
			);

			setWonText(
				winnerTeamResult.mapOr("Gewonnen hat: ???", (winnerTeam) => {
					return `Gewonnen hat: Team "${winnerTeam.name}"`;
				})
			);
		};
		void determineWinnerTeam();
	}, [queryClient, team1, team2, trpc.game.determineWinnerTeam]);

	return (
		<section className="col-span-full my-8 grid grid-cols-subgrid grid-rows-3 gap-2 lg:col-start-2 lg:col-end-6">
			<h1 className="col-span-full place-self-center">{wonText}</h1>
			<Button
				type="button"
				className="col-span-full mx-10 md:col-start-2 md:col-end-4 md:mx-0"
				onClick={() => {
					void navigate("/teams", { replace: true });
				}}
			>
				Neues Spiel
			</Button>
			<Button
				disabled={isAudioPlaying}
				type="button"
				className="col-span-full mx-10 md:col-start-2 md:col-end-4 md:mx-0"
				onClick={() => {
					gameStore.getState().setIsAudioPlaying(true);
				}}
			>
				Punktestand vorlesen
			</Button>
		</section>
	);
};

// source/browser-application/game-over/GameOver.vue
<script setup lang="ts">
import { useRouter } from "vue-router";
import { storeToRefs } from "pinia";
import { onMounted, ref } from "vue";
import { tryOrElse } from "true-myth/task";
import { useGameStore } from "../game-store/game-store.js";
import { useTRPCClientStore } from "../trpc-client-store/trpc-client-store.js";

const router = useRouter();
const gameStore = useGameStore();
const { trpcClient } = useTRPCClientStore();
const { team1, team2, isAudioPlaying } = storeToRefs(gameStore);

const wonText = ref("");

onMounted(async () => {
	const winnerTeamResult = await tryOrElse(
		(error: unknown) => {
			return new Error("Could not determine winner team", { cause: error });
		},
		async () => {
			return trpcClient.game.determineWinnerTeam.query({ team1: team1.value, team2: team2.value });
		}
	);

	wonText.value = winnerTeamResult.mapOr("Gewonnen hat: ???", (winnerTeam) => {
		return `Gewonnen hat: Team "${winnerTeam.name}"`;
	});
});

async function startNewGame(): Promise<void> {
	await router.push({ name: "teams", replace: true });
}
</script>

<template>
	<section class="col-span-full my-8 grid grid-cols-subgrid grid-rows-3 gap-2 lg:col-start-2 lg:col-end-6">
		<h1 class="col-span-full place-self-center">{{ wonText }}</h1>

		<button type="button" class="btn col-span-full mx-10 md:col-start-2 md:col-end-4 md:mx-0" @click="startNewGame">
			Neues Spiel
		</button>

		<button
			:disabled="isAudioPlaying"
			type="button"
			class="btn col-span-full mx-10 md:col-start-2 md:col-end-4 md:mx-0"
			@click="isAudioPlaying = true"
		>
			Punktestand vorlesen
		</button>
	</section>
</template>
